### ISSUE TITLE
panic: invalid argument

### ISSUE THREAD

**Issue by wuchaowei2012** [daulet/tokenizers#17]
The issue is not resolved, so I create it one more time. I tried docker, make build, but no matter what I do, the issue is still not resolved.

i finish to make build, but when i test example/main.go, the following error was found:

➜  tokenizers git:(main) ✗ go run example/main.go
---  invalid argument
panic: invalid argument

goroutine 1 [running]:
main.main()
        /home/zhaopanpan/aigc/tokenizers/example/main.go:13 +0x396
exit status 2

**Comment by daulet** [comment]
are you synced up to main branch? do you have local changes? [line 13](https://github.com/daulet/tokenizers/blob/main/example/main.go#L13) does not panic.
