### ISSUE TITLE
memory issues when using tokenizers

### ISSUE THREAD

**Issue by homily707** [daulet/tokenizers#19]
As I utilize the tokenizer, I've observed a continuous rise in memory consumption. 
Based on the discussions in https://github.com/golang/go/issues/53440 and the insights provided by https://dgraph.io/blog/post/manual-memory-management-golang-jemalloc/, it appears that the issue stems from glibc not returning memory to the operating system enough.

Considering this, I'm curious: is there any possibility that tokenizers might be adapted to utilize alternative memory allocators like jemalloc or tcmalloc in the future?

**Comment by daulet** [comment]
before we discuss memory allocators, do you have a repro to examine? Tokenizer config is the biggest memory consumer, and you can release that memory with `Tokenizer.Close()`. Are you reusing tokenizer struct or are you creating multiple instances?

**Comment by lwabish** [comment]
> before we discuss memory allocators, do you have a repro to examine? Tokenizer config is the biggest memory consumer, and you can release that memory with `Tokenizer.Close()`. Are you reusing tokenizer struct or are you creating multiple instances?

In my case, at first I am using a single struct wrapping a tokenizer instance(initiated by `tokenizers.FromFile()`)and pass this struct into a http handler to act as a tokenizer server.
In this case, `Tokenizer.Close()` is never invoked and memory keeps going up.

After seeing your reply, I changed my tokenizer server to initiate an instance inside a http handler `tokenizers.FromBytes(in.tokenizerBytes)` but the request delay has to goes up to 200ms, which is really expensive.

So I wonder In my use case as a tokenizer server, is there any better approach to solve both problems(memory got recycled and doesn't have to initiate an tokenizer instance per request)

**Comment by daulet** [comment]
> After seeing your reply, I changed my tokenizer server to initiate an instance inside a http handler tokenizers.FromBytes(in.tokenizerBytes) but the request delay has to goes up to 200ms, which is really expensive.

yeah don't do that, you were already doing the right thing by reusing it, just checking that you are not instantiating it multiple times.
